"use client";

import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import { FileText, Mail, CheckCircle2 } from "lucide-react";
import { cn } from "@/lib/utils";

interface CardSpec {
  key: string;
  className: string;
  rotate: number;
  z: number;
  floatDelay: string;
  content: React.ReactNode;
}

const LINE = "h-1.5 rounded-full bg-current opacity-15";

function ResumeCard() {
  return (
    <div className="w-40 rounded-lg border border-border bg-surface p-3 shadow-xl sm:w-48 sm:p-4">
      <div className="flex items-center gap-1.5 text-primary">
        <FileText className="h-3.5 w-3.5" />
        <span className="text-[10px] font-semibold uppercase tracking-wide">Resume</span>
      </div>
      <div className={cn(LINE, "mt-3 w-3/4 text-foreground")} />
      <div className={cn(LINE, "mt-1.5 w-1/2 text-foreground")} />
      <div className="mt-3 space-y-1.5">
        <div className={cn(LINE, "w-full text-muted-foreground")} />
        <div className={cn(LINE, "w-5/6 text-muted-foreground")} />
        <div className={cn(LINE, "w-full text-muted-foreground")} />
      </div>
      <div className="mt-3 inline-flex items-center rounded-full bg-brand-gradient px-2 py-0.5 text-[9px] font-bold text-white">
        ATS 94
      </div>
    </div>
  );
}

function CoverLetterCard() {
  return (
    <div className="w-36 rounded-lg border border-border bg-surface p-3 shadow-xl sm:w-44 sm:p-4">
      <div className="flex items-center gap-1.5 text-primary">
        <Mail className="h-3.5 w-3.5" />
        <span className="text-[10px] font-semibold uppercase tracking-wide">Cover Letter</span>
      </div>
      <p className="mt-3 text-[9px] italic text-muted-foreground">Dear Hiring Manager,</p>
      <div className="mt-2 space-y-1.5">
        <div className={cn(LINE, "w-full text-muted-foreground")} />
        <div className={cn(LINE, "w-full text-muted-foreground")} />
        <div className={cn(LINE, "w-2/3 text-muted-foreground")} />
      </div>
      <p className="mt-3 text-[9px] text-foreground">— Generated by AI</p>
    </div>
  );
}

function MatchBadge() {
  return (
    <div className="flex items-center gap-1.5 rounded-full border border-border bg-surface px-3 py-1.5 shadow-xl">
      <CheckCircle2 className="h-3.5 w-3.5 text-success" />
      <span className="text-xs font-semibold text-foreground">91% match</span>
    </div>
  );
}

const CARDS: CardSpec[] = [
  {
    key: "resume",
    className: "left-[2%] top-[6%] sm:left-[6%] sm:top-[10%]",
    rotate: -14,
    z: 60,
    floatDelay: "0s",
    content: <ResumeCard />,
  },
  {
    key: "cover-letter",
    className: "right-[2%] top-[16%] sm:right-[7%] sm:top-[18%]",
    rotate: 12,
    z: 30,
    floatDelay: "1.2s",
    content: <CoverLetterCard />,
  },
  {
    key: "match",
    className: "left-[8%] top-[62%] sm:left-[13%] sm:top-[58%]",
    rotate: -6,
    z: 80,
    floatDelay: "2.4s",
    content: <MatchBadge />,
  },
];

/** Documents "explode" into a fanned 3D arrangement on load, then float gently with a subtle mouse-parallax tilt. Decorative — hidden below lg since there's no room for it beside the hero text. */
export function HeroExplode() {
  const sceneRef = useRef<HTMLDivElement>(null);
  const [tilt, setTilt] = useState({ x: 0, y: 0 });

  useEffect(() => {
    function handlePointerMove(e: PointerEvent) {
      const x = (e.clientX / window.innerWidth - 0.5) * 2;
      const y = (e.clientY / window.innerHeight - 0.5) * 2;
      setTilt({ x: y * -6, y: x * 6 });
    }
    window.addEventListener("pointermove", handlePointerMove);
    return () => window.removeEventListener("pointermove", handlePointerMove);
  }, []);

  return (
    <div
      className="pointer-events-none absolute inset-0 hidden lg:block"
      style={{ perspective: "1400px" }}
      aria-hidden
    >
      <div
        ref={sceneRef}
        className="absolute inset-0 transition-transform duration-300 ease-out"
        style={{
          transformStyle: "preserve-3d",
          transform: `rotateX(${tilt.x}deg) rotateY(${tilt.y}deg)`,
        }}
      >
        {CARDS.map((card, i) => (
          <motion.div
            key={card.key}
            className={cn("absolute", card.className)}
            style={{ transformStyle: "preserve-3d" }}
            initial={{ opacity: 0, scale: 0.4, x: 0, y: 0, rotate: 0, z: 0 }}
            animate={{ opacity: 1, scale: 1, rotate: card.rotate, z: card.z }}
            transition={{ type: "spring", stiffness: 90, damping: 14, delay: 0.5 + i * 0.15 }}
          >
            <div className="animate-float" style={{ animationDelay: card.floatDelay }}>
              {card.content}
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
